enum ORDER {
  GECKO_ASC,
  GECKO_DESC,
  MARKET_CAP_ASC,
  MARKET_CAP_DESC,
  VOLUME_ASC,
  VOLUME_DESC,
  COIN_NAME_ASC,
  COIN_NAME_DESC,
  PRICE_ASC,
  PRICE_DESC,
  HOUR_24_ASC,
  HOUR_24_DESC,
  TRUST_SCORE_DESC,
  NAME_ASC,
  NAME_DESC,
  OPEN_INTEREST_BTC_ASC,
  OPEN_INTEREST_BTC_DESC,
  TRADE_VOLUME_24H_BTC_ASC,
  TRADE_VOLUME_24H_BTC_DESC,
}

enum STATUS_UPDATE_CATEGORY {
  GENERAL,
  MILESTONE,
  PARTNERSHIP,
  EXCHANGE_LISTING,
  SOFTWARE_RELEASE,
  FUND_MOVEMENT,
  NEW_LISTINGS,
  EVENT,
}

enum STATUS_UPDATE_PROJECT_TYPE {
  COIN,
  MARKET,
}

enum EVENT_TYPE {
  EVENT,
  CONFERENCE,
  MEETUP,
}
